[versions]
# build config
compileSdk = "34"
java-major = "17"
java = "17"
# billing
google-billing = "7.0.0"
# plugin
# https://maven.google.com/web/index.html?q=build#com.android.tools.build:gradle
android-plugin = "8.5.0"
android-tools-common = "31.5.1"
google-services = "4.4.2"
# https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md
spotless = "7.0.0.BETA1"
# androidx
androidx-appcompat = "1.7.0"
androidx-annotation = "1.8.1"
androidx-lifecycle-common = "2.8.3"
androidx-core = "1.13.1"
androidx-collection = "1.4.1"
androidx-fragment = "1.8.1"
androidx-room = "2.6.1"
androidx-hilt-compose = "1.2.0"
androidx-cardview = "1.0.0"
androidx-recyclerview = "1.3.2"
androidx-swiperefreshlayout = "1.1.0"
androidx-viewpager = "1.1.0-alpha01"
androidx-viewpager2 = "1.1.0"
androidx-transition-ktx = "1.5.0"
androidx-media2 = "1.3.0"
androidx-media3 = "1.3.1"
androidx-multidex = "2.0.1"
androidx-exifinterface = "1.3.7"
androidx-localbroadcastmanager = "1.1.0"
androidx-legacy-support-core-utils = "1.0.0"
androidx-sqlite = "2.4.0"
androidx-activity-compose = "1.9.0"
exoplayer = "2.19.1"
# firebase
firebase-analytics = "22.0.1"
firebase-messaging = "24.0.0"
auto-service = "1.0.1"
# appsflyer
appsflyer-core = "6.9.0"
appsflyer-google-referrer = "2.2"
# ui
androidx-constraintlayout = "2.1.4"
material = "1.12.0"
# other official library
hilt = "2.43.2"
# test
junit = "4.13.2"
androidx-test-core = "1.6.1"
androidx-test-runner = "1.6.1"
androidx-test-rules = "1.6.1"
androidx-test-orchestrator = "1.5.0"
androidx-test-ext = "1.2.1"
androidx-test-espresso = "3.6.1"
truth = "1.1.3"
# third party
mmkv = "1.2.14"
hilt-compose-navigation-factory = "1.2.0"
coil = "2.6.0"
guava = "31.1-android"
fastjson = "1.2.83"
commons-io = "2.15.1"
okhttp = "4.10.0"

[libraries]
# androidx
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle-common" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle-common" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "androidx-viewpager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "androidx-transition-ktx" }
androidx-media2 = { module = "androidx.media2:media2-session", version.ref = "androidx-media2" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "androidx-media3" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }
androidx-legacy-support-core-utils = { module = "androidx.legacy:legacy-support-core-utils", version.ref = "androidx-legacy-support-core-utils" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidx-sqlite" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
# Firebase
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
# ExoPlayer
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exoplayer-extension-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }
exoplayer-extension-cronet = { module = "com.google.android.exoplayer:extension-cronet", version.ref = "exoplayer" }
# ui
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
# billing
google-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "google-billing" }
# plugin dependencies
plugin-source-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
plugin-source-android-common = { module = "com.android.tools:common", version.ref = "android-tools-common" }
plugin-source-android-ddmlib = { module = "com.android.tools.ddms:ddmlib", version.ref = "android-tools-common" }
plugin-source-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
# hilt
hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-compose" }
hilt-compose-navigation-factory = { module = "net.lachlanmckee:hilt-compose-navigation-factory", version.ref = "hilt-compose-navigation-factory" }
hilt-compose-navigation-factory-compiler = { module = "net.lachlanmckee:hilt-compose-navigation-factory-compiler", version.ref = "hilt-compose-navigation-factory" }
# test
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
hilt-androidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
# third party
mmkv = { module = "com.tencent:mmkv-static", version.ref = "mmkv" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
# appsflyer
appsflyer-core = { module = "com.appsflyer:af-android-sdk", version.ref = "appsflyer-core" }
appsflyer-google-referrer = { module = "com.android.installreferrer:installreferrer", version.ref = "appsflyer-google-referrer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
java-library = { id = "org.gradle.java-library" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
hilt-android = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

[bundles]
hilt-navigation = ["hilt-navigation-compose", "hilt-compose-navigation-factory"]
hilt-compiler = ["hilt-compiler", "hilt-compose-navigation-factory-compiler"]
